spring.application.name=attendance-backend

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=attendance_db
server.error.include-stacktrace=never
server.error.include-message=never
jwt.secret=MySuperSecretKeyForAttendanceProject12345678901234567890
jwt.expiration=3600000